In [1]:
import numpy as np

from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding

In [2]:
reviews = [
    'nice food',
    'amazing retaurant',
    'too good',
    'just loved it!',
    'will go again',
    'horrible food',
    'never go there',
    'poor service',
    'poor quality',
    'needs improvement'
]

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [6]:
one_hot('amazing restaurant',30)

[26, 12]

In [21]:
vocab_size = 50
encoded_reviews = [one_hot(words,vocab_size) for words in reviews]
encoded_reviews

[[9, 2],
 [33, 30],
 [39, 15],
 [44, 8, 42],
 [19, 15, 11],
 [24, 2],
 [22, 15, 34],
 [8, 15],
 [8, 18],
 [2, 8]]

In [22]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
padded_reviews

array([[ 9,  2,  0],
       [33, 30,  0],
       [39, 15,  0],
       [44,  8, 42],
       [19, 15, 11],
       [24,  2,  0],
       [22, 15, 34],
       [ 8, 15,  0],
       [ 8, 18,  0],
       [ 2,  8,  0]])

In [23]:
embeded_vector_size = 4
model = Sequential()
model.add(Embedding(vocab_size,embeded_vector_size,input_length=max_length,name='embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [24]:
X = padded_reviews
y = sentiment

In [25]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 3, 4)              200       
_________________________________________________________________
flatten_2 (Flatten)          (None, 12)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 13        
Total params: 213
Trainable params: 213
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.fit(X,y,epochs=100,verbose=0)

In [27]:
loss, accuracy = model.evaluate(X,y)

1/1 [==============================] - 0s 128ms/step - loss: 0.5712 - accuracy: 1.0000


In [30]:
weights = model.get_layer('embedding').get_weights()[0]
weights

array([[-0.11775602,  0.05533473,  0.15132238,  0.05260024],
       [-0.04837435, -0.00752747, -0.046825  ,  0.02167599],
       [ 0.08344674, -0.13695589,  0.07995927,  0.12047408],
       [ 0.0317269 ,  0.04062722,  0.03912517, -0.0165597 ],
       [-0.0027114 ,  0.00352954,  0.02987161, -0.02373582],
       [ 0.00787561,  0.03988859, -0.00633067, -0.03012482],
       [ 0.04427383, -0.02743127, -0.01623851, -0.03486298],
       [ 0.01903299,  0.03576832, -0.03765491,  0.02807185],
       [ 0.07356758, -0.07457057,  0.11631926,  0.11915495],
       [-0.13593566,  0.07220952, -0.11316455, -0.13662705],
       [-0.02015909, -0.01779   , -0.0361008 ,  0.00564035],
       [ 0.12665534, -0.05307688, -0.10412727, -0.11887114],
       [-0.03449415,  0.02479091, -0.02322661,  0.03489019],
       [-0.03998243,  0.02437359,  0.02686775,  0.04416216],
       [ 0.02366124,  0.00329938,  0.01463094,  0.03545043],
       [ 0.07902931, -0.03023708,  0.03439111,  0.04569805],
       [-0.00897926, -0.

In [31]:
weights[11]

array([ 0.12665534, -0.05307688, -0.10412727, -0.11887114], dtype=float32)